return {
  -- General Functionality
  'wbthomason/packer.nvim',
  'nvim-lua/plenary.nvim',
  'windwp/nvim-autopairs',
  'numToStr/Comment.nvim',
  'JoosepAlviste/nvim-ts-context-commentstring',
  'kyazdani42/nvim-web-devicons',
  'kyazdani42/nvim-tree.lua',
  'akinsho/bufferline.nvim',
  'moll/vim-bbye',
  'nvim-lualine/lualine.nvim',
  'akinsho/toggleterm.nvim',
  'ahmedkhalf/project.nvim',
  'lewis6991/impatient.nvim',
  'lukas-reineke/indent-blankline.nvim',
  'goolord/alpha-nvim',
  'RRethy/vim-illuminate',
  'nvim-telescope/telescope.nvim',
  'nvim-treesitter/nvim-treesitter',
  'lewis6991/gitsigns.nvim',
  'folke/lua-dev.nvim',
  'tpope/vim-surround',
  'tpope/vim-repeat',
  'norcalli/nvim-colorizer.lua',
  'vimwiki/vimwiki',
  'folke/which-key.nvim',
  'felipec/vim-sanegx',
  'sindrets/diffview.nvim',
  -- Color Schemes,
  'folke/tokyonight.nvim',
  -- Completion,
  'hrsh7th/nvim-cmp',
  'hrsh7th/cmp-buffer',
  'hrsh7th/cmp-path',
  'saadparwaiz1/cmp_luasnip',
  'hrsh7th/cmp-nvim-lsp',
  'hrsh7th/cmp-nvim-lua',
  -- Snippets,
  'L3MON4D3/LuaSnip',
  'rafamadriz/friendly-snippets',
  -- LSP/DAP,
  'williamboman/mason.nvim',
  'jose-elias-alvarez/null-ls.nvim',
  'neovim/nvim-lspconfig',
  'williamboman/mason-lspconfig.nvim',
  'mfussenegger/nvim-dap',
  'rcarriga/nvim-dap-ui',
}
