#!/bin/sh
xrandr 	--dpi 109 --fb 4480x1633 \
	--output DP-2 --mode 2560x1440 --pos 1920x0 \
	--output HDMI-0 --mode 1920x1080 --pos 0x553
setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
remaps &		# run the remaps script, switching caps/esc and more; check it for more info

autostart="mpd picom dunst unclutter pipewire"

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
