vim.defer_fn(function()
    pcall(require, "impatient")
end, 0)

require('config.options')
require('funcs').bootstrap()
require('plugins')
require('config.autocmds').setup()
require('config.filetypes').setup()
require('config.icons').setup()
require('funcs').map('general')
