vim.defer_fn(function()
    pcall(require, "impatient")
end, 0)

require('config.options')
require('funcs').bootstrap()
require('plugins')
require('config.autocmdlist')
require('config.filetypelist')
require('funcs').map('general')
